### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by tmcw** [tmcw-up-for-adoption/chroniton#18]
* [ ] weather data through the years (noaa or nasa?)
* [ ] census population data
* [ ] earthquakes, storms

**Comment by lxbarth** [comment]
OSM progress https://github.com/mapbox/data/issues/677#issuecomment-70185284

**Comment by tmcw** [comment]
Sea temperatures http://www.cpc.ncep.noaa.gov/products/GIS/GIS_DATA/sst_oiv2/index.php

**Comment by tmcw** [comment]
moon phases https://github.com/mourner/suncalc#moon-illumination with optional wolves howling
