### ISSUE TITLE
support duration mode

### ISSUE THREAD

**Issue by tmcw** [tmcw-up-for-adoption/chroniton#5]
in which the bounds are absolute times but the scale shows relative duration. for runs.

**Comment by tmcw** [comment]
@sgillies in your GeoJSON-ld-related investigation into the magic of spacetime, did you get any aha moments about how to represent something like a duration?

Like:

I go on a ride at 2pm, and want to show relative time (my 2-hour bike ride) versus 2pm on a scale. Do you, in code, represent this as 2-4pm with the difference in some arbitrary division, like seconds or milliseconds? Or as a Date object from the epoch?

**Comment by sgillies** [comment]
@tmcw here's the state of GeoJSON time: https://github.com/geojson/geojson-ld/blob/master/time.md#proposal-in-a-nutshell.

Ride as an event-like feature with route as geometry and 2-4pm as "when." It doesn't capture all of the essence of a ride, though, or the GPX type features that you might need (speed at different points, etc).
